### ISSUE TITLE
How to get GSX account?

### ISSUE THREAD

**Issue by user-me** [filipp/gsxlib#30]
Hi, I was reading the links from Apple sites but not sure if I don't understand or individual or some small business cannot get Apple account to use the details to get like unlocking status and country from IMEI number and similar?

Could you pleaseprovide more information and point me if it is possible to get an account?

Thank you very much

**Comment by redonm** [comment]
Use this free gsx account but do not change the password

**Comment by redonm** [comment]
Freegsxaccount.blogspot.com

**Comment by user-me** [comment]
Hi, I tried but I did not see the file.
