### ISSUE TITLE
IMEI Search

### ISSUE THREAD

**Issue by henry1000** [filipp/gsxlib#40]
Hello,

We have been using GSXLIB for over a month now, and since this morning we are experiencing a weird error when searching for IMEI on our internal software. We have narrowed the issue down to the connection between gsxlib and GSX.

We would like to know if anyone else is experiencing this? Or if there is any solution for it?

Yours Sincerely,
Henry

**Comment by filipp** [comment]
What kind of error are you experiencing?

**Comment by henry1000** [comment]
Hello Filip,

Apparently it was a problem with GSX servers.

Yours Sincerely,
Henry
