### ISSUE TITLE
New Generation WSDL AND SSL (Secure Sockets Layer) certificate process

### ISSUE THREAD

**Issue by alopezruiz** [filipp/gsxlib#42]
GSX is changing due phishing problems...

"New Generation WSDL (web services description language). Integrating with this update requires completion of the SSL (Secure Sockets Layer) certificate process"

We love your code and used it very intense... so... could you help us adapting it to the new GSX API process? Are you planning that?

Thanks you very much!

**Comment by filipp** [comment]
I just got the announcement yesterday. Just sent the request for access to Apple and will make the necessary changes to the library as soon as I have access to the next gen API.

**Comment by alopezruiz** [comment]
You make me very happy!, btw, the current API is new generation or legacy?

Thanks you

**Comment by filipp** [comment]
I *think* the current API is what they're starting to refer to as "legacy", but to be honest I'm not sure what the exact differences are. The latest announcement referred only to authentication - not sure if there are any other differences in implementation. Maybe someone else here has already played with it and can say?

I've sent the CSR files to Apple today so should be able to start testing soon.

**Comment by henry1000** [comment]
We are currently just waiting for IP whitelisting, the process to have the certificates approved and install them on our server, took us around 5 weeks.

On the 9th of April we should have our IP's whitelisted.

**Comment by henry1000** [comment]
Well we got our IP whitelisted, but apparently there are more steps to finish the process.

What is the status on your end?

**Comment by filipp** [comment]
I got some certificates, waiting for whitelisting. No ETA.

**Comment by alopezruiz** [comment]
Hi! could you help me?

Do I have to send the CSR file?

And do I have to follow this instructions? (at https://gsxwsut.apple.com/apidocs/prod/html/WSFaq.html?user=asp)

"The FQDN is a very important field and Please be sure to provide the following value for this field:
For test environment CSR : Applecare-APP157-[SoldTo ID].Test.apple.com 
For production environment CSR : Applecare-APP157-[SoldTo ID].Prod.apple.com

For example,if your soldTo is 0000012345, the value should be Applecare-APP157-0000012345.Test.apple.com for test 
and Applecare-APP157-0000012345.prod.apple.com for production.
The leading zero's are important and the soldTo should always be 10 digits."

Thanks you.

**Comment by henry1000** [comment]
Yes you need to generate the CSR files, and send them.

Filip it is unfortunately that this is happening, we have passed the Certificates approval process, and also the IP whitelisting. Unfortunately there are a lot more steps in the process.

**Comment by henry1000** [comment]
Hello Fillip,

Today we have finished the process to connect to the test server, contact me by email, and I can work in getting you a test environment, so you can start developing the library.

- Henry

**Comment by filipp** [comment]
Sent you an email.

**Comment by henry1000** [comment]
Hello Fillip,

We got completely approved on GSX, meaning that we lost connection to Legacy WSDL, are you able to contact me, explaining how you do the requests on PHP, because everything that I try to authenticate gives me a weird error.

Contact me as soon as possible.

- Henry

**Comment by alopezruiz** [comment]
Hi I have also send the CSR ! Waiting for Apple.

BTW I have received  this information
 https://gsxwsut.apple.com/apidocs/ut/html/WSHome.html 
I think you got it, right?

Thanks you for your help ! Please if you don't mind post here some news about your new library! :-)

**Comment by alopezruiz** [comment]
And... meanwhile, regarding "client certificate"

"Work with your system administrator to install the Apple certificate on your server, in a manner that ensures the certificate is automatically attached to each API request sent to Apple. Depending on the technology, this may involve adding the certificate to the trust store."

Could you please tell me if I have to install in the Safari with my PHP application that connects to GSX API?, or in the PHP server where APP is stored? ... and do I have to develop something in PHP for this?

Thanks you in advance.

**Comment by troymccabe** [comment]
Has anyone had any luck authenticating against the new service? I'm assuming I'm missing something, but I'm unable to use the certs provided to actually get a successful response.

**Comment by Paullussie** [comment]
Hello everyone. Same here. I got the certs, but am not able to get a successful response.
No idea, what i am doing wrong. 
If somebody managed to use the new service i would greatly appreciated the method used.

Thanks in advance

**Comment by Kuchiru** [comment]
We've had our certificates approved as well and we were whitelisted, we get a good response via SoapUI so i assume we're set.
However once our IT guy started working on him he gets an error that the host could not be reached, however when we connect without the certs we get access denied :D

**Comment by Paullussie** [comment]
Hi, all.
After much trial and error i managed to authenticate against the new service (testing environment) and use the new API's.
I would like to share this, but am not familiar how to do so. Putting code here?

**Comment by Rojtjo** [comment]
@Paullussie, could you tell me which WSDL url you use for the UT environment?

**Comment by Paullussie** [comment]
@Rojtjo : 
wsdl: https://gsxapiut.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl

**Comment by Kuchiru** [comment]
@Paullussie You could use markdown to put some code here  https://guides.github.com/features/mastering-markdown/ , you could also put it on pastebin or create your own project on github and link it here.
Its your choice really :)

**Comment by Rojtjo** [comment]
Thank you @Paullussie!
It's the same url I was using but it just gives me a 404. Looks like I'll have to mail with support.

**Comment by Paullussie** [comment]
Hi, 
I only changed a little bit of Pilipps original code. 
Actually only added a couple of variables to the gsxlib class and altered the __construct method
I have put it on http://pastebin.com/Hi5x21gR (only the part before the first GSX API function)

This code works for me. (but if you find flaws in it , please let me know)

Note:
There is also in GSX a new API 'ReportedSymptomIssue' which is not yet in Pilipps code .
I tried to add this, but the result i got was not what i expected, so for this function i had to write some workarounds. if anybody is interested i can also put that in pastebin.

**Comment by Kuchiru** [comment]
The ReportedSymptomIssue is Apples latest attempt at making the API as bad as GSX is >_<

**Comment by alopezruiz** [comment]
Hi  @Paullussie, thanks you!

Just a question, does cert file could be stored in a folder in my php server, close to the code? 

For example

 private $local_cert = 'pem/Applecare-APP157-0000490035.Test.apple.com.chain.pem';

I get this error with your code, any help please?

Couldn't load from 'https://gsxapiut.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl' : failed to load external entity "https://gsxapiut.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl"

Is it related with de $local_cert var?

Thanks you!!

**Comment by Paullussie** [comment]
Hi @ alopezrule,
I am getting thesame error when using only the .pem provided from apple.
What i did is combine the privatekey.pem and the apple provided .pem into 1 .pem file.
i named this combined.pem and use that in my code.
i do not know if it matters, but my combined.pem file has first the privatekey.pem section and after that the apple.pem
like this:
cat privatekey.pem > combined.pem
cat Applecare_blaba.pem >> combined.pem

 The location of the .pem file does not matter (i think)
The passphrase of the privatekey has to go into:
private $passphrase = 'passphrase';

**Comment by karunamurthy** [comment]
We have a dedicated server, what are the steps to setup / install the received certificate on the server?
Do we also need to update the Apache config files?


We have a custom build application and am working to get this cracked.

receiving an error from the soap client  " HTTP Access Denied "  ???   what could be the issue?

**Comment by Kuchiru** [comment]
@karunamurthy Access denied usually means that the cert is not accepted or not included in the request to the server.
I'm guessing it is the latter in this case, unfortunately i have no clue on how to resolve this on your end.

I do hope that in the whitelisting process you included an IP just for a local testing environment so you can experiment freely (For example with SoapUI)

**Comment by Paullussie** [comment]
@karunamurthy. 
I did not have to setup/install any certificates into the apache environment.
Regarding the 'access denied' you can login normally into the GSX test environment? (i also had the access denied once and it turned out the testaccount was not yet accepted)

**Comment by filipp** [comment]
@Paullussie thanks for your changes! I'm testing them now and integrating them into the lib. Open source is awesome! :)

**Comment by Paullussie** [comment]
@filipp. thank you!
At the moment i have pretty much everything working . (used your lib as a basis, but modified some parts)
I can create repairrequests, lookups etc. So we are basically ready for aug. 16. :-)

**Comment by filipp** [comment]
I keep getting an "Invalid certificate for the SoldTo" error with every Sold-to I try. Trying to solve it with GSXWS support...

**Comment by russianryebread** [comment]
I am getting that error too (among other errors / connectivity timeouts)... Working with GSXWS support has been frustrating, to say the least, and we still have no resolution.  From what I can tell, there are some networking / configuration issues on their end that they are not telling us about.

**Comment by Paullussie** [comment]
Hi all,
I finished the tests succesfully and agreed with apple to go live on aug. 15
@filipp and @russianryebread, sorry to hear you have certificate issues. hopefully it will be solved soon.

**Comment by alopezruiz** [comment]
Dear @Paullussie 

As I still can't execute the script successfully... 

Could you help me with some tips? I mean:

a) 
The $local_cert has to be specified with "http://"
private $local_cert = 'http://XXX/aasp/gsxnew/pem/combined.pem';

b) 
How can I get the error because I haven't any with this code...

Just echo first $serialnumber

Thanks you!!!

>---
require 'gsxlib.php';

	$sold_to = 'xxxx';
	$username = 'yyyy';
	$password = 'zzzz';
	$serialnumber = 'C02GQPEADV13';
	
	echo $serialnumber;

	$gsx = GsxLib::getInstance($sold_to, $username, $password);
	echo $serialnumber;

>--

**Comment by filipp** [comment]
I got my cert working yesterday so I'll try and test and commit the changes tonight as well as update the documentation.

**Comment by Paullussie** [comment]
Hi @alopezruiz ,

a.) in my code i have a absolute path to the combined.pem. For example 
private @local_cert="/etc/ssl/apple/combined.pem";
i do not know if using a url for the @local_cert works. (probably not)

b.) i do not know exactly what you mean. The code i posted is basically only the modification for the _construct function in the gsxlib.php.

**Comment by Kuchiru** [comment]
@filipp will you add the reportedsymptomissue function as well or will that be reserved for later ?

Regards.

**Comment by filipp** [comment]
@Kuchiru I'm still not quite clear about what that even does. :) Is it something to do with AST? Is it required for creating repairs or just some lookup thing? The API call seems easy enough to implement - I'm just trying to understand what it's actually for. :)

**Comment by Kuchiru** [comment]
@filipp Basically carryIn was updated to include reportedsymptomcode and reportedsymptomissue.
The reportedsymptomissue was added because both of those codes are not optional.
What you normally do with reportedsymptomissue is you make one request with the serial number of the device and you get a list, which is a lot like the comptialist, this list contains the reportedsymptomcodes together with their descriptions. once you pick a symptomcode you have to re-request the reportedsymptomissue together with the serial number and the symptomcode to get the symtomissuecode list.

It's a very roundabout and useless function so far in my testing, but to do carry-in repairs you are forced to use it.. unfortunately.. 

If my explanation is confusing i can provide you with examples.

**Comment by alopezruiz** [comment]
Thanks you @Paullussie

Just one more help please...

I have to PEM files coming from Apple
- Applecare-APP157-00004xxxxx.Prod.apple.com.chain.pem
- Applecare-APP157-00004xxxxx.Test.apple.com.chain.pem
And PrivateKey for both
I made to combined.pem (with cat function), one for Prod and one for Test

What combined.pem do I have to use? the one which include ... Test.apple.com or the one which include Prod.apple.com?

Thanks you.

**Comment by filipp** [comment]
@Kuchiru oh crud. :( Thanks for bringing that up. I'll add that and test.

**Comment by Kuchiru** [comment]
@filipp np, and thanks.
If you need some test Serial numbers for the UT environment i can provide them via a private message or something :)

**Comment by Paullussie** [comment]
@alopezruiz ,
At the moment you are going to be testing, so in this case the test.apple.com...pem.

After succesfull testing completed, and you have a cut-over date from apple you have to use the prod.pem.

**Comment by alopezruiz** [comment]
Hi again @Paullussie 

Even when Apple said me I'm *onboard* with new WDSL?

Thanks you again for your help.

**Comment by Paullussie** [comment]
@Kuchiru ,@filipp,

I agree the symptomcode and issue function is pretty useless. 
But when doing a re-request after retrieving the symptomcode it is not neccessary to send the serialNumber again. Only the at stage-1 received symptomcode is enough.

**Comment by Kuchiru** [comment]
@Paullussie ah, i was wondering about that when i was writing it, thanks for the correction :)

**Comment by Paullussie** [comment]
@Kuchiru ,
Oh, sorry. i am not quite sure about that.
For production access i had to provide a 'lookup' request and response message to apple.
This has been approved and i can provide apple with a cutover date to production.

If 'onboard' means you can use production i do not really know. Best to ask apple about this.

**Comment by Paullussie** [comment]
@kuchiru, sorry. my last message was meant for @alopezruiz .

**Comment by Kuchiru** [comment]
@Paullussie no worries, just edit it :)

**Comment by karunamurthy** [comment]
Shoulld my server have a SSL certificate verified by CA or  can i have a self signed certificate installed to call the GSX web service?
e.g.  https:/myserver.com/gsxauth.php

**Comment by filipp** [comment]
The SSL changes are now in. I decided to implement the cert details as environment variables - that way you can define them wherever you want (or even share the same paths between different scripts in different languages) since the cert must be sent with each and every request. You still pass the username into the constructor so you can easily have multiple sessions open to GSX, if you want. The cert is sold-to specific so it might limit those who need access to different sold-tos from the same code, but that's not an issue for me and I'm open for suggestions if someone finds this unacceptable.

I also added a fetchSymptomIssue() method.So far it has only returned symtom codes and no issues, I'm guessing it's a SN-specific thing, but we should probably create a new ticket for this.

**Comment by Paullussie** [comment]
@filipp,

regarding the symptomissue. Did you first call the function with only the serialNumber and after retrieving the result calling the function again with only reportedSymptomCode parameter (ofcourse with 1 of the values retrieved from the serialNumber result?

**Comment by filipp** [comment]
@Paullussie yup. You got it! I'll have to keep trying with a part number/device combo that doesn't require certification since the UT account has no service certs or even tech IDs currently. Thanks!

**Comment by Paullussie** [comment]
@filipp ,
? what do you mean with Ut has no tech Id's? in my UT environment i found at least 1 tech ID which i use to createcarryinrepairs.

**Comment by filipp** [comment]
@Paullussie good. then you can run the test :) My Users/Technicians lists are empty in UT. Please create a new issue in GH if you have issues with that API - don't want to make a jumbo thread out of this one. :)

**Comment by eriktobben** [comment]
Hi!

I get the error "Cannot read SSL certificate". Does this mean that the .pem file is unreadable or that it doesn't fint it?

**Comment by Kuchiru** [comment]
@eriktobben are you sure you used the right passphrase ?

**Comment by eriktobben** [comment]
@Kuchiru 
I used the passphrase I used when creating the CSR. Is that wrong?

**Comment by Kuchiru** [comment]
You should use the passphrase you used to generate your own PEM file, combine the PEM you created with the one Apple sent you and it should work.

**Comment by eriktobben** [comment]
Okey. Now I've combined the file certreq_test.csr (from Apple) with privatekey_test.pem (from me) to certbundle.pem. Still the same error.

Just to clarify; when I sent the CSR with privatekey to Apple I created a password. Is this the password I should use?

The files I sent to Apple is:
certreq_prod.csr, certreq_test, privatekey_prod.pem, privatekey_test.pem

Sorry, but I've never worked with certificates before. Thanks for the help so far!

**Comment by Kuchiru** [comment]
Okay first of all, the CSR file is not a certificate, not in the sense apple is expecting.
You generated the CSR file from your own generated PEM file.
So you created your own local .PEM file and from that you created a CSR file, the CSR is the one you needed to send to Apple to have them create a UT and PROD .PEM file.
You need to combine your own (UT) .PEM file (not the CSR) and the (UT) .PEM file you got from Apple.
Use the passphrase you set for your local .PEM in the settings and it should work.

**Comment by eriktobben** [comment]
Thanks for the walkthrough. I did not get the AppleCare.something.test.PEM from Apple, just a file called AppleWWDRCA.cer. I have contacted Apple for the files.

Thanks again!

**Comment by eriktobben** [comment]
Just for information, I got this instruction from Apple:

If you wish to combine them to a KeyStore, I would choose the PFX format:
openssl pkcs12 -export -out certificate.pfx -inkey privatekey_ut.pem -in YOUR.Test.chain.pem 

After adding the certificate.pfx I am getting the following error:
SoapFault in gsxlib.php line 128: Could not connect to host

Is that because of the .pfx-certificate?

When trying with .pem I get the error:
SoapFault in gsxlib.php line 128: Invalid certificate for the SoldTo.

**Comment by karunamurthy** [comment]
@Kuchiru  @fillip @Paullussie Thanks a ton got my UT test success with the GSXLIB,  earlier issue i had was the certificate was placed in /root  i have now paced the certificates into the domain documents,  the full path was referenced,

**Comment by Kuchiru** [comment]
Glad you found it @karunamurthy it was the latter after all, right :p 
@eriktobben seems the last option you tried is a success, you just gotta get the sold-to right now.

**Comment by eriktobben** [comment]
@Kuchiru Thanks! Trying to figure this out with Apple. They are asking for RAW xml request and response. How can I get access to that from the lib?

**Comment by Paullussie** [comment]
@eriktobben, you can get the send xml and received xml with '__getLastRequest();' and '__getLastResponse();'
in the 'request' function, just before the return statement what i did was put the output of these statemants in a session_variable. ofcourse you can also echo them or email them:

just before the 'return' statement in the 'request' function:

echo $this->client->__getLastRequest();
echo $this->client->__getLastResponse();

Btw. offtopic: your name sounds dutch. are you dutch?

**Comment by eriktobben** [comment]
@Paullussie Thanks! I added the echo at the request function starting at line 577. But I am not able to see the request and response. I am using Laravel, and I am just getting the regular exception page with "SoapFault in gsxlib.php line 128: Invalid certificate for the SoldTo."

Hehe, I am from Norway :)

**Comment by filipp** [comment]
I added the environment variable GSX_DEBUG in the latest version - setting this to 1 will make it easier to track the XML requests and responses (they will be logged to syslog).

@eriktobben I had the same problem - it turned out to be an incorrect CN field in the cert. Hopefully you can sort it out with Apple.

**Comment by YesThatAllen** [comment]
For everyone having trouble* making certificates, I've posted a cheat-sheet form on my site here.

https://www.watchmanmonitoring.com/gsx-ssl

I made it to be a form so that the first part guides you through gathering just the right parts. The email it sends you will have literal copy & paste steps for you to carry out in `Terminal.app` and generate test & production `key` & `csr` files in just the right format.

For anyone who's already got their certificate from apple, you no longer need this. For anyone who's trying to figure out how to (re)make them, this is your Easy :radio_button: 

Of course there's some marketing with that, but it doesn't add you to any mailing list, etc. If you don't want to hand out your sold-to, you can enter 123456 and the form will work fine.. just replace 123456 with your actual sold-to before you run the commands we send.

I hope you find this useful.
-Allen Hancock

*The instructions on the readme provided by apple were anything but than helpful IMO.

**Comment by Kuchiru** [comment]
@YesThatAllen Nice! i'm sure that will be helpful for some people :D

**Comment by alopezruiz** [comment]
Hi everybody,

Is GSX new WDSL working right and now?

Thanks you

**Comment by Kuchiru** [comment]
@alopezruiz The new WSDL is live and working, i tested it earlier today.

**Comment by alopezruiz** [comment]
Thanks you @Kuchiru !!! It's working now for me also!

And special thanks to @filipp  for this fantastic library ... to @Paullussie for your version ... and all the people of this thread!

Thanks you!

**Comment by filipp** [comment]
Yup, looks good. I believe there are still some issues with creating escalations through the API, but the most important bits seem to work. Thanks to all for your help and feedback! <shameless plug>I recently open-sourced my commercial service management system for AASPs. It's pretty powerful and has been used at several companies for the past couple of years: https://github.com/fpsw/Servo</shameless plug>

**Comment by alopezruiz** [comment]
Wow! It's looks great!

Thanks you!

**Comment by Kuchiru** [comment]
Just for everyone that participated, you should check if your SSL certs are expiring soon and request new certificates.
Mine were created around this time as well and are expiring in about 45 days.
