### ISSUE TITLE
What about GSX Invoices?

### ISSUE THREAD

**Issue by alopezruiz** [filipp/gsxlib#45]
Hi,

Those who works in an AASP knows that they have to check every invoice coming for Apple because frequently they charge you for things not expected, for example, they charge sometimes because you don't send back the KBB part even you send it!

Is it there any possibility to improve this task of continuos review for example...

Download a List of Invoices, including ship-to,  with Type = "DEBIT MEMO" and "Module not received"?

Thanks you

**Comment by Kuchiru** [comment]
Hi,

According to the API documentation it is possible to get a list of invoice numbers based on a specific date(not a range of dates) and ship-to.
These invoice numbers can be used to fit in another request to get more details on one(!) invoice in XML format (not pdf).
Based on that data you can indeed filter out different types of invoices.

Wether this will be implemented in the lib is a question/request for @filipp but i imagine this will be low priority as there are probably more pressing matters to attend to.

**Comment by filipp** [comment]
Yup, should def. add this at some point. No ETA yet - let's wait for the dust from the API update to settle. :)

**Comment by alopezruiz** [comment]
Thanks you!!!

**Comment by alopezruiz** [comment]
Meanwhile...

   /** GET INVOICES FROM DATE ***/
      public function invoiceIDLookup($query)
    {
        $fields = array(
            'invoiceDate'  => ''
        );

			$query = array('invoiceDate' => $query);
            $query = array_merge($fields, $query);     
        
        $req = array('InvoiceIDLookupRequest' => array(
            'userSession' => array('userSessionId' => $this->session_id),
            'lookupRequestData' => $query 
        ));

        $response = $this->client->InvoiceIDLookup($req)->InvoiceIDLookupResponse;
		echo $response->repairNumber;
        return $response->lookupResponseData;
  }
  
  /** GET INVOICE DETAIL FROM INVOICEID  ***/
      public function invoiceDetailsLookup($query)
    {
        $fields = array(
            'invoiceID'  => ''
        );

			$query = array('invoiceID' => $query);
            $query = array_merge($fields, $query);     
        
        $req = array('InvoiceDetailsLookupRequest' => array(
            'userSession' => array('userSessionId' => $this->session_id),
            'lookupRequestData' => $query 
        ));

        $response = $this->client->invoiceDetailsLookup($req)->InvoiceDetailsLookupResponse;
		echo $response->repairNumber;
        return $response->lookupResponseData;
  }
