### ISSUE TITLE
Undefined property: stdClass::$appliedActivationDetails

### ISSUE THREAD

**Issue by eriktobben** [filipp/gsxlib#47]
Hi!

When I try to run the following as per the example provided in the lib:
$info = $gsx->fetchiOsActivation($serialnumber);
echo $info->appliedActivationDetails;

I get the following error:
Undefined property: stdClass::$appliedActivationDetails

Does anyone know how to get the ActivationDetails from GSX?

**Comment by TheAdmiral926** [comment]
Het eriktobben, the code in the example is grabbing the activation details of a iphone from GSX and giving them to you, if I'm not mistaken. Have you defined $serialnumber anywhere? could you provide your full php?

**Comment by eriktobben** [comment]
That is correct. Here is the code:

        $sold_to = 'XXXXXX';
     	$username = 'user@appleid.com';
     	$serialnumber = '523095309';

     	  $_ENV['GSX_CERT'] = 'path/to/cert';
    	  $_ENV['GSX_KEYPASS'] = 'passphrase';
    	  $gsx = GsxLib::getInstance($sold_to, $username);
          $info = $gsx->fetchiOsActivation($serialnumber);
          $info->appliedActivationDetails;
          var_dump($info);

When I var_dump the variable $info there is no value in the array called appliedActivationDetails.
Btw, is this the right call if I want to get the status of Find My iPhone?

**Comment by TheAdmiral926** [comment]
Hm, have you tried 
```
echo $info->appliedActivationDetails;
```
I have little experience with PHP, so var_dump may do the same thing. 
One other thing I would suggest is using the serial number of the phone instead of the IMEI. 
I haven't been able to authenticate my cert yet, I have my own issue open, so I'm not sure if this gives find my iphone info.

**Comment by eriktobben** [comment]
Hi! Yes, I have tried that. This is what I was using when the error displayed.

**Comment by eriktobben** [comment]
Has anyone else been able to fetch Find my iphone activation status in UT?

**Comment by Kuchiru** [comment]
Are you able to fetch the warranty details for the serial numbers you are using ?

**Comment by eriktobben** [comment]
Yes, I am. When using $gsx->warrantyStatus() with the same serial I get information back. But the field "public 'activationLockStatus' => string '' (length=0)" is empty..

**Comment by Kuchiru** [comment]
Since you're using the UT environment i wouldn't count on the data thats present to be complete.

**Comment by eriktobben** [comment]
Okey, but shouldn't I at least get the appliedActivationDetails as an empty string in the array?

**Comment by Kuchiru** [comment]
I don't know, i haven't used the activationdetails in our UT tests so i cannot answer that, i did have issues testing with non UT serial numbers though.

**Comment by eriktobben** [comment]
I got a lot of info from that serial.

  object(stdClass)[285]
  public 'serialNumber' => string 'DNQM1210DTC0' (length=12)
  public 'imeiNumber' => string '013170000972024' (length=15)
  public 'lastUnbrickDate' => string '' (length=0)
  public 'unbricked' => string 'false' (length=5)
  public 'unlocked' => string 'false' (length=5)
  public 'initialActivationPolicyID' => string '1' (length=1)
  public 'initialActivationPolicyDetails' => string 'Unassigned factory default - Apple carriers only. SIM Swap triggers rebricking.' (length=79)
  public 'nextTetherPolicyID' => string '1' (length=1)
  public 'nextTetherPolicyDetails' => string 'Unassigned factory default - Apple carriers only. SIM Swap triggers rebricking.' (length=79)
  public 'bluetoothMacAddress' => string '' (length=0)
  public 'partDescription' => string '' (length=0)

Do you know which field is Find my iphone activation?

**Comment by Kuchiru** [comment]
What you're looking for is hidden away in warrantyStatus, activationLockStatus will be present in the response with a message that it is active.

**Comment by Kuchiru** [comment]
@eriktobben 
Has this solved your issue ?
If so, please close the issue you created, otherwise they keep piling up :D

**Comment by eriktobben** [comment]
I am onboarding production today, and I will check if this is working.

I will close it after that :) Thanks for the help! :+1:

**Comment by eriktobben** [comment]
Hi again. I got a confirmation that I am onboarded production, but after changing the the certificate and removed UT from $environment and also added the correct wsdl, I get the following error:

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://gsxapi.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl' : failed to load external entity "https://gsxapi.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl"

Do anyone know what can cause this error? (It was working before changing from UT)

**Comment by eriktobben** [comment]
Figured it out, I entered the wrong password for the new certificate. Everything is working great!
