### ISSUE TITLE
Cant find iPad by serial number

### ISSUE THREAD

**Issue by eriktobben** [filipp/gsxlib#48]
Hi!

I am trying to fetch details on a iPad Mini. I have checked via GSX and the serial number is valid and displays data, but when entering the same s/n in gsxlib there are problems.

When I am using the fetchiOsActivation(), I get the following error:
Provided serial number does not belong to an iOS Device.Please Enter an ios serial number.

When using the warrantyStatus(), I get the following error:
The serial number you entered is not valid. Please enter the serial number as it appears on the customer's unit.

**Comment by Kuchiru** [comment]
Hi @eriktobben 
Is this in the UT or Production environment ?

**Comment by eriktobben** [comment]
Hi! This is in UT.

**Comment by Kuchiru** [comment]
Okay, what you're experiencing is expected behaviour.
The UT environment does not run on the live database and most serial numbers have to be manually registered in there for them to work. Ask GSXWS for some test serial numbers and they will provide :)

**Comment by eriktobben** [comment]
Ahh, I see. Thanks! :)
