### ISSUE TITLE
Issue with both windows and mac PHP SOAP Exception

### ISSUE THREAD

**Issue by DatenThielt** [filipp/gsxlib#52]
Good Afternoon.

I am attempting to get your PHP Library running, After attempting to create my own and hitting the same road block,  It seems no matter what I do , I always end up with the error 

PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://gsxapi.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl' : failed to load external entity "https://gsxapi.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl" in C:\inetpub\wwwroot\gsxlib\gsxlib.php:104

I have attempted to connect to GSX on both Mac and Linux.  Just as a main note, I developed a C# library for GSX which works perfectly on both machines.  (Unfortunately Mono on mac has its quirks and we have decided to move to a PHP Solution)

I have been at it about 4 hours non stop, Trying everything from not verifying host names, to disabling the cache. 

As stated before I know the credentials, and certificates I am using are good and valid. due to them working with the C# library,  This library also uses the certificate file rather than root store. 

Any help would be much appreciated! Thanks

**Comment by patrickgill** [comment]
It's not gsxlib, it's Apple. The URL is timing out.
If you have a local version of the file you could use that for now.

[The GSX API page](https://gsxwsut.apple.com/apidocs/prod/html/WSArtifacts.html?user=asp)

**Comment by filipp** [comment]
Yeah, PHP probably has different defaults for connection timeouts than C#'s SOAP/HTTP library - so that's why it might be working under C#. Or it might just be intermittent, but doesn't sound like it's an issue with the library or how you're using it.

**Comment by DatenThielt** [comment]
Thanks for the reply's so far. 

Unfortunately I forgot to mention I did download the local WSDL Fils with the Class definition files,  and tried to point the soap client to that file, with the same error.  I assume that its not timing out on the WSDL File but the endpoint for the service.

Is there any way to increase the overall time out globally?  Thanks!  (I will google this in the mean time)

**Comment by filipp** [comment]
default_socket_timeout in your php.ini

**Comment by DatenThielt** [comment]
Unfortunately this did not work.  

I first set the default socket time out in the php to 600, then 6000 just to test but the error reported above is instantly thrown,  

At this point I am starting to think maybe PHP reads the certificate differently,  I am going to get Fiddler out and check what its sending, I will report my findings here.

**Comment by YesThatAllen** [comment]
We dealt with a clients's issue on line 104, and it turned out to be a crossed set of SSL Keys. They were using the UT key with Production certs.. of course things didn't work.

We narrowed down the issue, and used this to validate the pair:

> $ openssl x509 -noout -modulus -in path/to/server.crt | openssl md5
> $ openssl rsa -noout -modulus -in path/to/server.key | openssl md5

The resulting numbers should match, or the keypair is not right.

**Comment by DatenThielt** [comment]
Thanks for the response YesThatAllen,  Unfortunately our keys are 100% paired correctly, (Ran the command to be sure and they were identical) as they are the same certs from our working C# appliocation.

Fiddler is providing to be fruitless and giving me no real information at all.  other than an odd error about SSL handshake being to many bytes but still being supported.   Time to get wireshark out

**Comment by DatenThielt** [comment]
I have solved the issue!

As we know the Lib was not at fault,  But actually one of our firewalls in the building,  For some reason the way PHP Deals with https requests differs from our C# counterpart,  This was causing our internal firewall to block the request.

Thank you for the help everyone!

P.S Just a small gripe, It might be worth adding the soapClient catch error to the return string,  Rather than the hard coded string that currently sits there,  Might help people in the future.  String I am referring to is 

$error = 'Authentication with GSX failed. Does this account have access to ' .$environment."?\n";

it could use $e just to give a better description of the error.

Thanks again!
