### ISSUE TITLE
Can't make Soap Client

### ISSUE THREAD

**Issue by mpereira13** [filipp/gsxlib#53]
I'm using the old gsxlib, now i want to update the lib and receive always this error:
"Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://gsxapi.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl' : failed to load external entity "https://gsxapi.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl" in /var/www/html/Client/sip/php/class/gsxlib.php:105 Stack trace: #0 "

Is this a bug? Anyone can help ?

**Comment by Kuchiru** [comment]
Hi,

This can be caused my multiple things, IPs not whitelisted yet, wrong certs, wrong passphrases..

see: https://github.com/filipp/gsxlib/issues?utf8=%E2%9C%93&q=is%3Aissue+failed+to+load+external+entity

**Comment by mpereira13** [comment]
Solve, wrong certs, tks a lot Kuchiru.
