### ISSUE TITLE
Problems with GSX?

### ISSUE THREAD

**Issue by eriktobben** [filipp/gsxlib#54]
Hi!

I am having trouble connecting to GSX, I get these two errors randomly:

SOAP-ERROR: Parsing Schema: can't import schema from 'https://gsxapi.apple.com/wsdl/emeaAsp/gsx-global-requestResponse-elements.xsd'

and

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://gsxapi.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl' : failed to load external entity "https://gsxapi.apple.com/wsdl/emeaAsp/gsx-emeaAsp.wsdl"

This has been working fine for over two months, and I know the serial number is correct.

Is anyone else having problems with GSX, or have any suggestions?

**Comment by eriktobben** [comment]
I am also getting a 504 Gateway Time-out from time to time...

**Comment by filipp** [comment]
Yeah, same here. I think it's just the GSX servers. You could add some retry logic to your app, or maybe we could even add it to the lib itself...

**Comment by Kuchiru** [comment]
There were some issues with the gsx api docs website, remote WSDL's were not reachable at that time.
Switching to a local WSDL will prevent such issues in the future :)

**Comment by eriktobben** [comment]
I found that the problem is occurring every time I have rebooted the server. 10-15 min after reboot, it works again.
