### ISSUE TITLE
Authentication with GSX failed.

### ISSUE THREAD

**Issue by csteelatgburg** [filipp/gsxlib#59]
I recently setup access to gsxit.apple.com with the necessary certificates and my IP address has been whitelisted. When using gsxlib I receive the following error:

Fatal error: Uncaught exception 'GsxException' with message 'Authentication with GSX failed. Does this account have access to it? 

Here are is my code without the confidential bits:
$sold_to = "my 10 digit sold to account number";
$username = "my email address with admin privileges on gsxit.apple.com";
$serialnumber = "serial number for my computer";

include 'gsxlib.php';
  $_ENV['GSX_CERT'] = '/path/to/certbundle.pem';
  $_ENV['GSX_KEYPASS'] = 'certificate passphrase';

  $gsx = GsxLib::getInstance($sold_to, $username, 'it');
  $info = $gsx->warrantyStatus($serialnumber);
  echo $info->productDescription;

I have read through the other issues and can't figure out what might be causing the authentication to fail.

Thanks.

**Comment by eriktobben** [comment]
Hi!

Are you sure that the Apple ID is able to log in to gsxit.apple.com?
Also, is your server whitelisted for the IT environment?

Is this only a problem when trying to authenticate to IT, or does it happen on UT as well?

**Comment by csteelatgburg** [comment]
I submitted this issue while waiting to hear back from Apple support. They said that our sold to account had not been activated for the IT environment yet but that should happen tonight. I'm not sure why they didn't do that automatically when they processed the certificates and whitelisted the IP, but oh well. I'm going to assume that's the problem and will close this issue.

At this point we only have the certificates setup for IT so I can't test UT.

**Comment by eriktobben** [comment]
Yeah, Apple does not (as far as I know) automatically onboard you to all environments at the same time.

By the way; Remember to include $ship_to in your warrantyStatus request as the IT environment has the new API upgrade. Example: https://github.com/filipp/gsxlib/blob/master/examples/warranty_status.php

Good luck!
